name: Auto 10 Commits

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch and 10 commits
        run: |
          BRANCH="auto-commits-$(date -u +'%Y%m%dT%H%M%SZ')"
          git checkout -b "$BRANCH"

          for i in $(seq 1 10); do
            FILE="auto_commit_${i}.txt"
            echo "Auto commit #$i at $(date -u)" > "$FILE"
            git add "$FILE"
            git commit -m "automation: add $FILE"
          done

          git push -u origin "$BRANCH"
